### ISSUE TITLE
Add drive access tiers

### ISSUE THREAD

**Issue by wlan0** [minio/direct-csi#145]
```kubectl direct-csi drives access-tier --drives *** --nodes *** Hot/Warm/Cold```

This should set `drive.status.accessTier to "Hot/Cold/Warm"` in the drive object. Drives of a particular tier can be chosen by setting the following parameter in the storage class

```
direct.csi.min.io/access-tier: "Hot" or "Cold" or "Warm"
```

**Comment by sstubbs** [comment]
I see there has been a lot of work done on this project which is great. I ended up using LXD containers instead of Kubernetes which isn't ideal when everything else is on Kubernetes. I will be deploying minio on more servers fairly soon and am wondering if direct csi going to be a viable option. I notice openebs and localpv are recommended by the minio operator now.

**Comment by wlan0** [comment]
@sstubbs yes, the access tier PR is in the works, you can see under the Pull Requests tab. Along with that PR, we’ll be bumping up our minor version from 1.2 to 1.3 and API version from alpha1 to beta1. It should be merged by this Friday.

DirectCSI is being deployed in customer environments now and it has been fairly stable. I would say you can start trying it out in a PoC environment and test it out.
