### ISSUE TITLE
Better document what DIRECT CSI is for and what it does

### ISSUE THREAD

**Issue by haslersn** [minio/direct-csi#30]
Currently the [README.md](../blob/master/README.md) doesn't explain to me, as someone who never heared of DIRECT CSI before, what exactly it does. Through some research I found out, that it is a Kubernetes Operator that

* provides a storage class,
* provisions a PV whenever a PVC referencing the storage class is created and
* uses block devices directly attached to the Kubernetes node as backing storage for the created PVs.

Is this correct?

However, for me there are some open questions:

* Can this be seen as an alternative to [local-path-provisioner](https://github.com/rancher/local-path-provisioner)?
* What are the differences, advantages and disadvantages compared to local-path-provisioner?
* Does DIRECT CSI provide file storage or block storage, or can we even choose per PVC?
* If DIRECT CSI supports file storage but uses block devices as backing storage, then what file system does it use internally?
* **Most important:** Are the privisioned PVs so-called local volumes (i.e. pods claiming them can only be scheduled on one node)?
* Can I use a different number and size of backing block devices per Kubernetes node?

**Comment by wlan0** [comment]
@haslersn We have revamped the documentation

**Comment by ngbrown** [comment]
Can you expand on why this storage vs some other options.

The documentation compares against LocalVolume provisioner, but Kubernetes blog already [recommends](https://kubernetes.io/blog/2018/04/13/local-persistent-volumes-beta/#automating-local-volume-creation-and-deletion) [Local Persistence Volume Static Provisioner](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner) for a more automated approach.

Also, there is [TopoLVM](https://github.com/topolvm/topolvm). It appears that TopoLVM is resizing partitions on changes to spec size. Is Direct-CSI is using XFS quotas instead of resizing the partition?
