### ISSUE TITLE
how to bring to ready status drive with exists ext4 partition?

### ISSUE THREAD

**Issue by Slach** [minio/direct-csi#331]
Hello team,
thanks a lot for your great efforts

could you clarify something for me?
is XFS required for Direct-CSI?

my `kubectl direct-csi drives list --all` return following result
```
 DRIVE       CAPACITY  ALLOCATED  FILESYSTEM  VOLUMES  NODE        ACCESS-TIER  STATUS
 /dev/sda    256 GiB   5.1 GiB    ext4        -        slach-mini  hot          Available
 /dev/sdb    256 GiB   20 GiB     ext4        -        slach-mini  -            Unavailable
 ```
 
 how to bring /dev/sda to ready status without apply format?
 could direct CSI just use exists ext4 partition?

**Comment by wlan0** [comment]
DirectCSI always takes full control of the drive - therefore we cannot work with pre-formatted drives. 
 
If you want to make it "Ready", call `kubectl direct-csi drive format $drive-path $node-name`. DirectCSI will format it with xfs (since we use xfs-quota, this is the only allowed filesystem). We found that xfs has the best balance of performance and scale after running it in production for many years. Other filesystems did not show the same properties unfortunately.

**Comment by Slach** [comment]
thanks a lot for explaination
