### ISSUE TITLE
Find Model and Serial number of drives in the new drive discovery mechanism

### ISSUE THREAD

**Issue by wlan0** [minio/direct-csi#81]

**Comment by immanuelfodor** [comment]
Would this work with virtual drives as e.g. `sdb` attached by QEMU? 

```
$ ls -la /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1
lrwxrwxrwx. 1 root root 9 Dec 25 10:58 /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1 -> ../../sdb
```

And a mildly related question: would the device discovery be able to use the `by-id` device as permanent device name instead of relying on the kernel-dependent `sdX` names? I'm a bit worried of relying on sda/sdb names generally in Linux.

**Comment by wlan0** [comment]
@immanuelfodor We have changed the implmenetation to utilize major and minor numbers to discover drives rather than paths in `/dev`. This has given us the advantage of being able to reliably find all block devices. 

This change is included in the v1.0.0 release we made yesterday. Please try it out and let us know if things work well in your environment.

**Comment by immanuelfodor** [comment]
Oh, wow, didn't know that, thanks!

**Comment by wlan0** [comment]
this is not needed anymore
